version: '3.10'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
